export enum ModulesCodes {
    org = 'org',
    user = 'user',
    workspace = 'workspace',
    category = 'category',
    subcategory = 'subcategory',
    product = 'product',
    workflow = 'workflow',
    action = 'action',
    order = 'order',
    release = 'release',
    nonrelease = 'nonrelease',
}
export enum ModulesSettings {
    categorySettings = 'categorySettings',
    subCategorySettings = 'subCategorySettings',
    productSettings = 'productSettings',
    userSettings = 'userSettings',
    workspaceSettings = 'workspaceSettings',
    nonReleaseSettings = 'nonReleaseSettings',
    releaseSettings = 'releaseSettings',
    orderSettings = 'orderSettings',
    workflowSettings = 'workflowSettings',
    actionSettings = 'actionSettings',
}