apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uploader
  name: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/sleepr-378423/uploader/production
          name: uploader
          env:
            - name: PORT
              value: '3003'
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: set value
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: clientSecret
            - name: GOOGLE_OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google
                  key: refreshToken
            - name: SMTP_USER
              value: test@mailinator.com
          ports:
            - containerPort: 3003
