apiVersion: v1
kind: Service
metadata:
  labels:
    app: uploader
  name: uploader
spec:
  ports:
    - name: 'tcp'
      port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: uploader
  type: ClusterIP
